#!/usr/bin/env bash
set -e
DIR_TEST_ENV=travis_venv
export GAIATEST_ACKNOWLEDGED_RISKS=true
export GAIATEST_SKIP_WARNING=true

root=tests/python/gaia-ui-tests/gaiatest
b2g=`find b2g -follow -name "b2g-bin" | tail -n 1`
profile=profile
gaiatest="python $root/cli.py"

echo "run the tests!"
. $DIR_TEST_ENV/bin/activate
$gaiatest --app=b2gdesktop \
          --binary=$b2g \
          --profile=$profile \
          --type=b2g \
          --html-output artifacts/gaia_ui_tests_report.html \
          --restart \
          $root/tests/functional/everythingme/manifest.ini \
          $root/tests/functional/ftu/manifest.ini \
          $root/tests/functional/homescreen/manifest.ini \
          $root/tests/functional/keyboard/manifest.ini \
          $root/tests/functional/lockscreen/manifest.ini \
          $root/tests/functional/marketplace/manifest.ini \
          $root/tests/functional/messages/manifest.ini \
          $root/tests/functional/persona/manifest.ini \
          $root/tests/functional/settings/manifest.ini \
          $root/tests/functional/system/manifest.ini \
          $root/tests/accessibility/lockscreen/manifest.ini
