#! /bin/bash -v

# not using -e here because we use code failure for other things here.
RETRY=10

function waiting_port {
  for i in $(seq 1 $RETRY); do
    nc -z localhost $1
    if [ $? -eq 0 ]; then return; fi
    sleep 1
  done
  echo "Waiting for server on port $1 failed."
  exit 1
}

echo "Starting test-agent-server"
make test-agent-server &

echo 'Starting B2G Desktop'

./b2g/b2g-bin -profile `pwd`/profile-debug --runapp 'Test Agent' &
waiting_port 8080
