#! /bin/bash -ve
echo 'Downloading b2g-desktop'
make b2g

echo 'Downloading & installing node dependencies'
make common-install

echo 'Create all app list file'
TEMP_APP_LIST=`mktemp /tmp/app.list.XXXXXX`
echo -e 'apps/*\ndev_apps/*\noutoftree_apps/*' > $TEMP_APP_LIST

echo 'Downloading xulrunner-sdk and making profile for testing (more than 5 minutes)'
NO_LOCK_SCREEN=1 DEBUG=1 DESKTOP=0 WGET_OPTS=-nv GAIA_APP_CONFIG=$TEMP_APP_LIST make
