#! /bin/bash -vex

make node_modules

pwd
ls

./node_modules/.bin/js-test-agent test \
  --this-chunk=${THIS_CHUNK:=1} \
  --total-chunks=${TOTAL_CHUNKS:=1} \
  --server ws://localhost:8789 \
  --reporter dot
