#!/bin/sh

show_help() {
  echo 'addpref <debug|enable-sw|disable-sw|god|nogod|skia|noskia|marionette|logs|rehash-manifest|selection>'
  echo 'addpref <key> <value>'
  echo "   Put value between single _and_ double quotes if it's a string."
  echo 'addpref <help|-help|--help>'
}

addpref() {
  key="$1"
  value="$2"

  echo "Waiting for device..."
  adb wait-for-device
  adb shell <<-EOF
    stop b2g
    cd /data/b2g/mozilla/*.default/
    echo 'user_pref("$key", $value);' >> prefs.js
    start b2g
    exit
EOF
}

if [ -z "$1" ] ; then
  echo "ERROR: Please supply at least one argument."
  show_help
  exit 1
fi

case "$1" in
  debug)
    addpref 'devtools.debugger.forbid-certified-apps' 'false'
    addpref 'devtools.debugger.prompt-connection' 'false'
    ;;
  skia)
    addpref 'gfx.canvas.azure.accelerated' 'true'
    ;;
  noskia)
    addpref 'gfx.canvas.azure.accelerated' 'false'
    ;;
  marionette)
    addpref 'marionette.defaultPrefs.enabled' 'true'
    ;;
  logs)
    addpref 'ril.debugging.enabled' 'true'
    addpref 'mms.debugging.enabled' 'true'
    addpref 'network.debugging.enabled' 'true'
    addpref 'dom.mozApps.debug' 'true'
    ;;
  rehash-manifest)
    addpref 'gecko.buildID' '"1"'
    ;;
  selection)
    addpref 'selectioncaret.enabled'  'on'
    addpref 'selectioncaret.noneditable' 'on'
    ;;
  god)
    addpref 'dom.apps.developer_mode' 'true'
    ;;
  ungod)
    addpref 'dom.apps.developer_mode' 'false'
    ;;
  enable-sw)
    addpref 'dom.serviceWorkers.interception.enabled' 'true'
    addpref 'devtools.webconsole.filter.serviceworkers' 'true'
    addpref 'dom.serviceWorkers.enabled' 'true'
    ;;
  disable-sw)
    addpref 'dom.serviceWorkers.interception.enabled' 'false'
    addpref 'devtools.webconsole.filter.serviceworkers' 'false'
    addpref 'dom.serviceWorkers.enabled' 'false'
    ;;
  help|-help|--help)
    show_help
    exit 0
    ;;
  *)
    if [ -z "$2" ] ; then
      echo "ERROR: Please supply 2 arguments if you don't use a shortcut."
      show_help
      exit 1
    fi
    addpref "$1" "$2"
    ;;
esac

