/* Copied from a local install of exec-sync to avoid NPM dependency hell */
/*
Copyright (c) 2011-2012 Jérémy Faivre <contact@jeremyfa.com>

Permission is hereby granted, free of charge, to any person obtaining
a copy of this software and associated documentation files (the
'Software'), to deal in the Software without restriction, including
without limitation the rights to use, copy, modify, merge, publish,
distribute, sublicense, and/or sell copies of the Software, and to
permit persons to whom the Software is furnished to do so, subject to
the following conditions:

The above copyright notice and this permission notice shall be
included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED 'AS IS', WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/
// Generated by CoffeeScript 1.3.3
(function() {
  var FFI, fs, getOutput, libc, tmpDir, uniqId, uniqIdK;

  FFI = require("ffi-prebuilt");

  libc = new FFI.Library(null, {
    "system": ["int32", ["string"]]
  });

  fs = require("fs");

  uniqIdK = 0;

  uniqId = function() {
    var prefix;
    prefix = 'tmp';
    return prefix + (new Date()).getTime() + '' + (uniqIdK++) + ('' + Math.random()).split('.').join('');
  };

  tmpDir = function() {
    var dir, name, _i, _len, _ref;
    _ref = ['TMPDIR', 'TMP', 'TEMP'];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      name = _ref[_i];
      if (process.env[name] != null) {
        dir = process.env[name];
        if (dir.charAt(dir.length - 1) === '/') {
          return dir.substr(0, dir.length - 1);
        }
        return dir;
      }
    }
    return '/tmp';
  };

  getOutput = function(path) {
    var output;
    output = fs.readFileSync(path);
    fs.unlinkSync(path);
    output = "" + output;
    if (output.charAt(output.length - 1) === "\n") {
      output = output.substr(0, output.length - 1);
    }
    return output;
  };

  module.exports = function(cmd, returnOutAndErr) {
    var dir, error, id, result, stderr, stdout;
    if (returnOutAndErr == null) {
      returnOutAndErr = false;
    }
    id = uniqId();
    stdout = id + '.stdout';
    stderr = id + '.stderr';
    dir = tmpDir();
    cmd = "" + cmd + " > " + dir + "/" + stdout + " 2> " + dir + "/" + stderr;
    libc.system(cmd);
    result = getOutput("" + dir + "/" + stdout);
    error = getOutput("" + dir + "/" + stderr);
    if (returnOutAndErr) {
      return {
        stdout: result,
        stderr: error
      };
    } else {
      if (error !== '') {
        throw new Error(error);
      }
      return result;
    }
  };

}).call(this);
