#! /bin/bash -ve

TEST_ENV="travis_venv"

echo "installing virtualenv"
curl https://raw.github.com/pypa/virtualenv/master/virtualenv.py | python - $TEST_ENV

echo "creating venv"
virtualenv $TEST_ENV
. $TEST_ENV/bin/activate

ROOT=$PWD
echo "setting up gaia-ui-tests dependencies"
cd tests/python/gaia-ui-tests/
python setup.py develop

cd $ROOT;

echo "Downloading b2g-desktop"
make b2g

echo "building profile"
DESKTOP_SHIMS=1 make
