#!/usr/bin/env bash
set -e
ROOT=$PWD
echo "setting up gaia-ui-tests dependencies"
source tests/travis_ci/venv.sh
cd tests/python/gaia-ui-tests/
python setup.py develop

cd $ROOT;

echo "remove the previously created dir b2g/ and profile/ if they exist"
rm -rf  b2g/
rm -rf  profile/

echo "downloading b2g-desktop"
make b2g

echo "building profile"
make
