#! /bin/bash -ve
export GAIATEST_ACKNOWLEDGED_RISKS=true
export GAIATEST_SKIP_WARNING=true

root=tests/python/gaia-ui-tests/gaiatest
b2g=`find b2g -follow -name "b2g-bin" | tail -n 1`
profile=profile
gaiatest="python $root/cli.py"

$gaiatest --app=b2gdesktop \
          --binary=$b2g \
          --profile=$profile \
          --type=b2g \
          --repeat 10 \
          --timeout 1000 \
          --restart \
          $root/tests/functional/messages/test_sms_contact_input_validation.py \
          $root/tests/functional/calendar/test_calendar_new_event_appears_on_all_calendar_views.py \
