#! /bin/bash -ve
export GAIATEST_ACKNOWLEDGED_RISKS=true
export GAIATEST_SKIP_WARNING=true

root=tests/python/gaia-ui-tests/gaiatest
b2g=`find b2g -follow -name "b2g-bin" | tail -n 1`
profile=profile
gaiatest="python $root/cli.py"

$gaiatest --app=b2gdesktop \
          --binary=$b2g \
          --profile=$profile \
          --type=b2g \
          --restart $root/tests/manifest.ini
