language: node_js

node_js:
  - '0.10'

env:
  - TEST_SUITE=unit

install:
  - npm install
  - ./node_modules/.bin/mozilla-download ./firefox/ --product firefox --branch mozilla-central
  - export FIREFOX_NIGHTLY_BIN="./firefox/firefox/firefox-bin"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script: "npm test"
