//
// This file is automatically generated: DO NOT EDIT.
// To change these values, create a camera.json file in the
// distribution directory with content like this: 
//
//   {
//     "maxImagePixelSize": 6000000,
//     "maxSnapshotPixelSize": 4000000, 
//     "avgJpegCompressionRatio": 24 
//   }
//
// Optionally, you can also define variables to specify the
// minimum EXIF preview size that will be displayed as a
// full-screen preview by adding a property like this:
//
// "requiredEXIFPreviewSize": { "width": 640, "height": 480}
//
// If you do not specify this property then EXIF previews will only
// be used if they are big enough to fill the screen in either
// width or height in both landscape and portrait mode.
//
var CONFIG_MAX_IMAGE_PIXEL_SIZE = 5242880;
var CONFIG_MAX_SNAPSHOT_PIXEL_SIZE = 5242880;
var CONFIG_AVG_JPEG_COMPRESSION_RATIO = 8;
var CONFIG_REQUIRED_EXIF_PREVIEW_WIDTH = 0;
var CONFIG_REQUIRED_EXIF_PREVIEW_HEIGHT = 0;
