#! /bin/bash -ve
echo 'Downloading Firefox'

curl https://s3-us-west-2.amazonaws.com/gaia-mozilla-b2g-builds/firefox-30.0a1.en-US.linux-x86_64.tar.bz2 > firefox.tar.bz2
tar -xjf firefox.tar.bz2

echo 'Downloading & installing node dependencies'
make common-install

echo 'Downloading xulrunner-sdk and making profile for testing (more than 5 minutes)'
DEBUG=1 DESKTOP=0 WGET_OPTS=-nv make
