#! /bin/bash -ve
time make node_modules

echo 'Downloading Firefox'
time ./node_modules/.bin/mozilla-download --product firefox \
                 --channel tinderbox \
                 --branch mozilla-central \
                 $PWD/firefox

echo 'Downloading & installing node dependencies'
time make common-install

echo 'Downloading xulrunner-sdk and making profile for testing (more than 5 minutes)'
time DEBUG=1 DESKTOP=0 WGET_OPTS=-nv make
