#! /bin/bash -ve
echo 'Downloading Firefox'
./node_modules/.bin/mozilla-download --product firefox \
                 --channel tinderbox \
                 --branch mozilla-central \
                 $PWD/firefox

echo 'Downloading & installing node dependencies'
make common-install

echo 'Downloading xulrunner-sdk and making profile for testing (more than 5 minutes)'
DEBUG=1 DESKTOP=0 WGET_OPTS=-nv make
