#! /bin/bash

# Exit if we encounter any bug
set -e

debugmessage=''

gaia_clear () {
	make clean &> /dev/null
}

error_handler () {
	printf '\e[41;30m x ---- fail\e[40;37m \n'
  printf $debugmessage
}

pass_handler () {
	printf '\e[42;30m v ---- pass\e[40;37m \n'
}

unit_test () {
	REPORTER=dot
	testfiles=$(find build/test/*.test.js)
	echo $testfiles
	./node_modules/.bin/mocha \
			--harmony \
			--reporter $REPORTER \
			--ui tdd \
			$testfiles
}


trap error_handler ERR

# Store all the distributions folder here
distributions=(distribution_tablet)

# Store locales test language
locales=(en-US zh-CN)

# Address of locale file
locale_url=http://hg.mozilla.org/gaia-l10n/LOCALEURL/archive/tip.tar.gz

printf 'Running unit test ...'
unit_test
pass_handler

printf 'make ...'
gaia_clear
debugmessage=$(make)
pass_handler

printf 'PRODUCTION=1 make ... '
gaia_clear
debugmessage=$(PRODUCTION=1 make)
pass_handler

printf 'SIMULATOR=1 make ...'
gaia_clear
debugmessage=$(SIMULATOR=1 make)
pass_handler

printf 'DEBUG=1 make ...'
gaia_clear
debugmessage=$(DEBUG=1 make)
pass_handler

printf 'GAIA_DISTRIBUTION_DIR=<distribution> make ...'
for distribution in ${distributions[@]}; do
	gaia_clear
	printf '\n  -DISTRIBUTION='$distribution' ... '
  debugmessage=$(GAIA_DISTRIBUTION_DIR=$distribution make)
	pass_handler
done

printf 'MOZILLA_OFFICIAL=1 make ...'
gaia_clear
debugmessage=$(MOZILLA_OFFICIAL=1 make)
pass_handler

printf 'LOCALES_FILE=<PATH_OF_LOCALES_FILE> LOCALE_BASEDIR=<PATH_OF_LOCALE_BASEDIR> make ...\n'
gaia_clear
if [ -d 'templocale' ]; then
	rm -rf templocale/*
else
	mkdir templocale
fi

pushd templocale &> /dev/null
touch locale.json
localeJSON='{'
for locale in ${locales[@]}; do
	mkdir $locale
	localeJSON+="\"$locale\": \"$locale\","
	curl -s ${locale_url/LOCALEURL/$locale} | tar xvz --strip-components=1 --directory=$locale  &> /dev/null
done
localeJSON="${localeJSON%?}}"
echo $localeJSON >> locale.json
popd &> /dev/null
debugmessage=$(LOCALES_FILE=templocale/locale.json LOCALE_BASEDIR=templocale make)
pass_handler
