#! /bin/bash -ve

echo "Downloading b2g-desktop"
time make b2g

# Install virtualenv and radicale on Travis.
time make caldav-server-install

echo "Building test profile"
time PROFILE_FOLDER=profile-test make
