#!/bin/sh

LINTED_DIRECTORIES="apps shared"

excluded_list=".jshintignore"
if [ ! -f $excluded_list ];
then
  exit 0
fi

hash gjslint > /dev/null 2>&1
if [ $? -eq 1 ];
then
  echo >&2 "You should install gjslint to lint your patch"
  echo >&2 "https://developers.google.com/closure/utilities/docs/linter_howto"
  exit 0
fi

# LINTED_FILES needs to be space-separated
diff_with_exclude=`git diff --staged --name-only --diff-filter=ACMRT -- $LINTED_DIRECTORIES | grep '\.js$' | tr '[:space:]' ' '`
if [ -z "$diff_with_exclude" ] ; then
  exit 0
fi

# Only test files xfailed in jshint in gjslint
xfailed=`git diff --staged --name-only --diff-filter=ACMRT -- $LINTED_DIRECTORIES | grep '\.js$' | comm -12 build/jshint-xfail.list - | tr '[:space:]' ' '`

if [ -n "$xfailed" ] ; then
  echo "gjslint:"
  LINTED_FILES="$xfailed" make -s gjslint || exit 1
fi

echo "jshint:"
# warn about files being xfailed
for file in $diff_with_exclude ; do
  grep $file build/jshint-xfail.list > /dev/null 2>&1 && \
   echo "$file is in the build/jshint-xfail.list - errors will be ignored. Please consider fixing lint errors and removing it from the build/jshint-xfail.list"
done

LINTED_FILES="$diff_with_exclude" make -s hint && echo "No errors - committing"
